version: '3.8'

services:

  neo4j:
    image: neo4j:4.2
    ports:
       - 7474:7474
       - 7687:7687
    environment:
       - NEO4J_AUTH=none 
    volumes:
       - type: volume
         source: neo4j-data
         target: /data


volumes:
  neo4j-data:

# http://localhost:7474/ 
