// _NE_ODSTRANI_

import java.awt.Color;

public class Test46 {

    private static final boolean T = true;
    private static final boolean F = false;

    public static void main(String[] args) {
        Igra igra = new Igra(new Igra.Celica[][]{{new Igra.Celica(T, T, T, F), new Igra.Celica(T, T, T, F), new Igra.Celica(T, T, F, T), new Igra.Celica(F, T, F, T), new Igra.Celica(F, T, F, F), new Igra.Celica(F, T, T, F), new Igra.Celica(T, T, F, T), new Igra.Celica(F, T, F, F), new Igra.Celica(F, T, T, T)}, {new Igra.Celica(T, F, F, T), new Igra.Celica(F, F, F, F), new Igra.Celica(F, T, T, T), new Igra.Celica(T, T, F, T), new Igra.Celica(F, F, F, T), new Igra.Celica(F, F, T, F), new Igra.Celica(T, T, F, F), new Igra.Celica(F, F, T, F), new Igra.Celica(T, T, T, F)}, {new Igra.Celica(T, T, F, T), new Igra.Celica(F, F, F, F), new Igra.Celica(F, T, F, T), new Igra.Celica(F, T, F, F), new Igra.Celica(F, T, F, T), new Igra.Celica(F, F, T, F), new Igra.Celica(T, F, F, F), new Igra.Celica(F, F, T, T), new Igra.Celica(T, F, T, F)}, {new Igra.Celica(T, T, T, T), new Igra.Celica(T, F, F, T), new Igra.Celica(F, T, F, T), new Igra.Celica(F, F, T, T), new Igra.Celica(T, T, T, T), new Igra.Celica(T, F, F, F), new Igra.Celica(F, F, T, F), new Igra.Celica(T, T, F, T), new Igra.Celica(F, F, T, F)}, {new Igra.Celica(T, T, T, T), new Igra.Celica(T, T, T, F), new Igra.Celica(T, T, T, F), new Igra.Celica(T, T, F, T), new Igra.Celica(F, T, T, F), new Igra.Celica(T, F, T, F), new Igra.Celica(T, F, T, F), new Igra.Celica(T, T, F, F), new Igra.Celica(F, F, T, T)}, {new Igra.Celica(T, T, F, T), new Igra.Celica(F, F, F, F), new Igra.Celica(F, F, T, T), new Igra.Celica(T, T, T, F), new Igra.Celica(T, F, T, T), new Igra.Celica(T, F, F, F), new Igra.Celica(F, F, F, F), new Igra.Celica(F, F, F, F), new Igra.Celica(F, T, T, T)}, {new Igra.Celica(T, T, T, F), new Igra.Celica(T, F, F, F), new Igra.Celica(F, T, F, T), new Igra.Celica(F, F, F, T), new Igra.Celica(F, T, F, T), new Igra.Celica(F, F, F, T), new Igra.Celica(F, F, T, T), new Igra.Celica(T, F, T, F), new Igra.Celica(T, T, T, F)}, {new Igra.Celica(T, F, T, F), new Igra.Celica(T, F, F, F), new Igra.Celica(F, T, F, F), new Igra.Celica(F, T, F, F), new Igra.Celica(F, T, T, F), new Igra.Celica(T, T, T, T), new Igra.Celica(T, T, F, F), new Igra.Celica(F, F, F, T), new Igra.Celica(F, F, T, F)}, {new Igra.Celica(T, F, T, T), new Igra.Celica(T, F, T, T), new Igra.Celica(T, F, F, T), new Igra.Celica(F, F, F, T), new Igra.Celica(F, F, F, T), new Igra.Celica(F, T, T, T), new Igra.Celica(T, F, F, T), new Igra.Celica(F, T, F, T), new Igra.Celica(F, F, T, T)}}, new Igra.Figura[]{new Igra.Pacman(4, 4, Color.GREEN), new Igra.Duh(7, 6, Color.GREEN), new Igra.Duh(6, 6, Color.RED), new Igra.Duh(8, 0, Color.GREEN), new Igra.Pacman(5, 5, Color.BLUE), new Igra.Duh(0, 2, Color.BLUE), new Igra.Pacman(8, 5, Color.BLUE)});
        igra.sproziRisanje(new String[]{"rezultat46.png", "860x660"});
    }
}
