version: '3.8'

services:

  mongodb:
    image: mongo:4-bionic
    volumes:
       - type: volume
         source: mongodb-data
         target: /data/db

  mongo-express:
    image: mongo-express:0.54
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
    ports:
      - 8081:8081


volumes:
  mongodb-data:

# http://localhost:8081/
