
public class Test50 {

    private static final boolean T = true;
    private static final boolean F = false;

    public static void main(String[] args) {

        boolean[][] m1 = {
            {F, T, T, T, F, F, F, T, F, F, F, F, F, F, F, F, F},
            {T, F, T, F, T, T, T, T, T, T, T, T, F, T, T, T, T},
            {T, T, F, F, T, T, F, T, T, T, F, F, T, T, T, T, F},
            {T, F, F, F, T, T, F, T, F, F, F, F, F, F, T, F, T},
            {F, T, T, T, F, F, T, F, T, F, T, F, F, F, F, F, F},
            {F, T, T, T, F, F, F, F, F, F, F, F, F, T, F, F, F},
            {F, T, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F},
            {T, T, T, T, F, F, F, F, F, T, F, F, F, F, F, F, T},
            {F, T, T, F, T, F, F, F, F, T, F, T, T, T, T, F, T},
            {F, T, T, F, F, F, F, T, T, F, F, F, F, F, F, F, F},
            {F, T, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F},
            {F, T, F, F, F, F, F, F, T, F, F, F, F, F, F, F, F},
            {F, F, T, F, F, F, F, F, T, F, F, F, F, F, T, F, T},
            {F, T, T, F, F, T, F, F, T, F, F, F, F, F, T, T, T},
            {F, T, T, T, F, F, F, F, T, F, F, F, T, T, F, F, F},
            {F, T, T, F, F, F, F, F, F, F, F, F, F, T, F, F, T},
            {F, T, F, T, F, F, F, T, T, F, F, F, T, T, F, T, F},
        };
        int[][] s1 = {
            {1, 2, 3, 7},
            {0, 2, 4, 5, 6, 7, 8, 9, 10, 11, 13, 14, 15, 16},
            {0, 1, 4, 5, 7, 8, 9, 12, 13, 14, 15},
            {0, 4, 5, 7, 14, 16},
            {1, 2, 3, 6, 8, 10},
            {1, 2, 3, 13},
            {1, 4},
            {0, 1, 2, 3, 9, 16},
            {1, 2, 4, 9, 11, 12, 13, 14, 16},
            {1, 2, 7, 8},
            {1, 4},
            {1, 8},
            {2, 8, 14, 16},
            {1, 2, 5, 8, 14, 15, 16},
            {1, 2, 3, 8, 12, 13},
            {1, 2, 13, 16},
            {1, 3, 7, 8, 12, 13, 15},
        };

        boolean[][] m2 = {
            {F, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T},
            {T, F, T, F, F, F, T, F, F, F, F, F, F, F, T, F, F},
            {T, T, F, F, T, T, T, F, T, F, F, T, F, T, T, F, F},
            {T, F, F, F, F, F, F, T, F, T, F, F, F, F, F, F, T},
            {T, F, T, F, F, T, T, T, F, T, F, T, F, T, F, F, T},
            {T, F, T, F, T, F, F, F, T, F, F, F, F, F, F, F, F},
            {T, T, T, F, T, F, F, F, F, F, F, F, F, F, F, F, F},
            {T, F, F, T, T, F, F, F, F, F, F, T, F, F, F, F, F},
            {T, F, T, F, F, T, F, F, F, T, T, F, T, T, T, T, F},
            {T, F, F, T, T, F, F, F, T, F, F, F, F, F, F, F, F},
            {T, F, F, F, F, F, F, F, T, F, F, T, F, F, T, T, F},
            {T, F, T, F, T, F, F, T, F, F, T, F, F, F, T, T, T},
            {T, F, F, F, F, F, F, F, T, F, F, F, F, F, F, F, F},
            {T, F, T, F, T, F, F, F, T, F, F, F, F, F, F, F, F},
            {T, T, T, F, F, F, F, F, T, F, T, T, F, F, F, F, F},
            {T, F, F, F, F, F, F, F, T, F, T, T, F, F, F, F, F},
            {T, F, F, T, T, F, F, F, F, F, F, T, F, F, F, F, F},
        };
        int[][] s2 = {
            {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16},
            {0, 2, 6, 14},
            {0, 1, 4, 5, 6, 8, 11, 13, 14},
            {0, 7, 9, 16},
            {0, 2, 5, 6, 7, 9, 11, 13, 16},
            {0, 2, 4, 8},
            {0, 1, 2, 4},
            {0, 3, 4, 11},
            {0, 2, 5, 9, 10, 12, 13, 14, 15},
            {0, 3, 4, 8},
            {0, 8, 11, 14, 15},
            {0, 2, 4, 7, 10, 14, 15, 16},
            {0, 8},
            {0, 2, 4, 8},
            {0, 1, 2, 8, 10, 11},
            {0, 8, 10, 11},
            {0, 3, 4, 11},
        };

        boolean[][] m3 = {
            {F, T, T, F, F, F, F, T, F, F, F, F, T, F, F, F, F},
            {T, F, F, F, F, F, F, F, F, F, F, T, F, F, F, F, F},
            {T, F, F, T, T, T, T, T, T, T, T, T, T, T, F, T, T},
            {F, F, T, F, T, F, T, T, T, T, T, T, T, T, T, F, T},
            {F, F, T, T, F, F, F, F, F, F, F, F, F, F, F, F, F},
            {F, F, T, F, F, F, F, F, F, F, F, T, F, F, F, F, F},
            {F, F, T, T, F, F, F, F, T, F, T, F, F, F, F, F, F},
            {T, F, T, T, F, F, F, F, T, T, T, T, T, T, T, T, T},
            {F, F, T, T, F, F, T, T, F, T, F, F, F, T, F, F, F},
            {F, F, T, T, F, F, F, T, T, F, F, F, F, F, F, F, F},
            {F, F, T, T, F, F, T, T, F, F, F, T, F, F, F, T, F},
            {F, T, T, T, F, T, F, T, F, F, T, F, T, F, T, T, F},
            {T, F, T, T, F, F, F, T, F, F, F, T, F, T, F, F, F},
            {F, F, T, T, F, F, F, T, T, F, F, F, T, F, T, T, T},
            {F, F, F, T, F, F, F, T, F, F, F, T, F, T, F, F, F},
            {F, F, T, F, F, F, F, T, F, F, T, T, F, T, F, F, T},
            {F, F, T, T, F, F, F, T, F, F, F, F, F, T, F, T, F},
        };
        int[][] s3 = {
            {1, 2, 7, 12},
            {0, 11},
            {0, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 15, 16},
            {2, 4, 6, 7, 8, 9, 10, 11, 12, 13, 14, 16},
            {2, 3},
            {2, 11},
            {2, 3, 8, 10},
            {0, 2, 3, 8, 9, 10, 11, 12, 13, 14, 15, 16},
            {2, 3, 6, 7, 9, 13},
            {2, 3, 7, 8},
            {2, 3, 6, 7, 11, 15},
            {1, 2, 3, 5, 7, 10, 12, 14, 15},
            {0, 2, 3, 7, 11, 13},
            {2, 3, 7, 8, 12, 14, 15, 16},
            {3, 7, 11, 13},
            {2, 7, 10, 11, 13, 16},
            {2, 3, 7, 13, 15},
        };

        boolean[][] m4 = {
            {F, T, T, F, F, F, F, F, F, F, F, F, F, F, F, F, F},
            {T, F, F, F, T, T, T, F, F, F, F, F, F, F, F, F, F},
            {T, F, F, T, F, F, F, F, F, T, F, F, T, T, F, F, F},
            {F, F, T, F, T, T, T, T, T, T, T, T, T, T, T, T, T},
            {F, T, F, T, F, F, F, T, T, T, F, T, F, T, F, T, T},
            {F, T, F, T, F, F, F, F, F, F, F, F, T, F, T, F, F},
            {F, T, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F},
            {F, F, F, T, T, F, F, F, T, F, T, F, F, F, F, F, F},
            {F, F, F, T, T, F, F, T, F, T, F, F, F, F, F, F, F},
            {F, F, T, T, T, F, F, F, T, F, F, F, F, F, F, F, F},
            {F, F, F, T, F, F, F, T, F, F, F, F, F, F, F, F, F},
            {F, F, F, T, T, F, F, F, F, F, F, F, F, F, F, F, F},
            {F, F, T, T, F, T, F, F, F, F, F, F, F, T, T, F, T},
            {F, F, T, T, T, F, F, F, F, F, F, F, T, F, T, T, T},
            {F, F, F, T, F, T, F, F, F, F, F, F, T, T, F, F, F},
            {F, F, F, T, T, F, F, F, F, F, F, F, F, T, F, F, T},
            {F, F, F, T, T, F, F, F, F, F, F, F, T, T, F, T, F},
        };
        int[][] s4 = {
            {1, 2},
            {0, 4, 5, 6},
            {0, 3, 9, 12, 13},
            {2, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16},
            {1, 3, 7, 8, 9, 11, 13, 15, 16},
            {1, 3, 12, 14},
            {1, 3},
            {3, 4, 8, 10},
            {3, 4, 7, 9},
            {2, 3, 4, 8},
            {3, 7},
            {3, 4},
            {2, 3, 5, 13, 14, 16},
            {2, 3, 4, 12, 14, 15, 16},
            {3, 5, 12, 13},
            {3, 4, 13, 16},
            {3, 4, 12, 13, 15},
        };

        boolean[][] m5 = {
            {F, T, F, F, F, F, F, F, F, F, T, F, F, F, F, F, F},
            {T, F, T, T, T, T, T, T, T, T, T, T, F, F, F, F, T},
            {F, T, F, T, F, F, T, T, F, F, F, T, F, F, T, T, F},
            {F, T, T, F, T, T, T, F, T, T, T, T, F, T, F, T, T},
            {F, T, F, T, F, T, F, F, F, F, F, F, F, F, F, F, T},
            {F, T, F, T, T, F, F, F, T, F, F, F, F, F, F, F, F},
            {F, T, T, T, F, F, F, T, F, F, T, T, T, F, F, F, T},
            {F, T, T, F, F, F, T, F, T, T, T, T, T, F, T, T, T},
            {F, T, F, T, F, T, F, T, F, F, F, F, F, F, T, F, F},
            {F, T, F, T, F, F, F, T, F, F, F, F, F, T, F, F, F},
            {T, T, F, T, F, F, T, T, F, F, F, T, T, T, T, T, F},
            {F, T, T, T, F, F, T, T, F, F, T, F, T, F, T, F, F},
            {F, F, F, F, F, F, T, T, F, F, T, T, F, F, F, F, F},
            {F, F, F, T, F, F, F, F, F, T, T, F, F, F, F, T, F},
            {F, F, T, F, F, F, F, T, T, F, T, T, F, F, F, T, F},
            {F, F, T, T, F, F, F, T, F, F, T, F, F, T, T, F, F},
            {F, T, F, T, T, F, T, T, F, F, F, F, F, F, F, F, F},
        };
        int[][] s5 = {
            {1, 10},
            {0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 16},
            {1, 3, 6, 7, 11, 14, 15},
            {1, 2, 4, 5, 6, 8, 9, 10, 11, 13, 15, 16},
            {1, 3, 5, 16},
            {1, 3, 4, 8},
            {1, 2, 3, 7, 10, 11, 12, 16},
            {1, 2, 6, 8, 9, 10, 11, 12, 14, 15, 16},
            {1, 3, 5, 7, 14},
            {1, 3, 7, 13},
            {0, 1, 3, 6, 7, 11, 12, 13, 14, 15},
            {1, 2, 3, 6, 7, 10, 12, 14},
            {6, 7, 10, 11},
            {3, 9, 10, 15},
            {2, 7, 8, 10, 11, 15},
            {2, 3, 7, 10, 13, 14},
            {1, 3, 4, 6, 7},
        };

        boolean[][] m6 = {
            {F, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T},
            {T, F, F, F, T, F, F, T, F, F, F, F, F, T, F, F, F},
            {T, F, F, T, T, F, T, T, T, F, T, F, F, F, F, T, F},
            {T, F, T, F, F, T, T, F, T, T, T, T, F, F, T, F, T},
            {T, T, T, F, F, T, F, F, F, F, F, F, F, T, F, T, F},
            {T, F, F, T, T, F, F, T, T, F, T, T, T, T, T, T, F},
            {T, F, T, T, F, F, F, F, F, T, F, T, F, T, F, T, T},
            {T, T, T, F, F, T, F, F, F, F, F, F, F, F, F, F, F},
            {T, F, T, T, F, T, F, F, F, F, F, F, T, F, T, F, T},
            {T, F, F, T, F, F, T, F, F, F, F, T, F, F, F, F, F},
            {T, F, T, T, F, T, F, F, F, F, F, F, F, F, F, F, F},
            {T, F, F, T, F, T, T, F, F, T, F, F, F, F, F, F, T},
            {T, F, F, F, F, T, F, F, T, F, F, F, F, F, F, T, F},
            {T, T, F, F, T, T, T, F, F, F, F, F, F, F, T, T, T},
            {T, F, F, T, F, T, F, F, T, F, F, F, F, T, F, F, T},
            {T, F, T, F, T, T, T, F, F, F, F, F, T, T, F, F, T},
            {T, F, F, T, F, F, T, F, T, F, F, T, F, T, T, T, F},
        };
        int[][] s6 = {
            {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16},
            {0, 4, 7, 13},
            {0, 3, 4, 6, 7, 8, 10, 15},
            {0, 2, 5, 6, 8, 9, 10, 11, 14, 16},
            {0, 1, 2, 5, 13, 15},
            {0, 3, 4, 7, 8, 10, 11, 12, 13, 14, 15},
            {0, 2, 3, 9, 11, 13, 15, 16},
            {0, 1, 2, 5},
            {0, 2, 3, 5, 12, 14, 16},
            {0, 3, 6, 11},
            {0, 2, 3, 5},
            {0, 3, 5, 6, 9, 16},
            {0, 5, 8, 15},
            {0, 1, 4, 5, 6, 14, 15, 16},
            {0, 3, 5, 8, 13, 16},
            {0, 2, 4, 5, 6, 12, 13, 16},
            {0, 3, 6, 8, 11, 13, 14, 15},
        };

        boolean[][] m7 = {
            {F, T, T, T, T, F, F, F, F, F, F, F, F, F, F, F, F},
            {T, F, F, F, F, T, T, F, F, F, F, T, F, F, F, F, F},
            {T, F, F, T, T, T, T, T, T, T, T, T, T, T, T, T, F},
            {T, F, T, F, F, F, F, F, F, F, T, F, F, T, F, F, F},
            {T, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F, F},
            {F, T, T, F, F, F, F, T, T, F, F, T, T, F, F, F, T},
            {F, T, T, F, F, F, F, F, F, T, F, F, T, F, F, F, F},
            {F, F, T, F, F, T, F, F, F, F, F, F, F, F, F, F, F},
            {F, F, T, F, F, T, F, F, F, F, F, F, F, F, F, F, F},
            {F, F, T, F, F, F, T, F, F, F, T, T, T, F, F, F, F},
            {F, F, T, T, F, F, F, F, F, T, F, F, F, T, T, F, T},
            {F, T, T, F, F, T, F, F, F, T, F, F, F, F, F, F, F},
            {F, F, T, F, F, T, T, F, F, T, F, F, F, T, T, T, T},
            {F, F, T, T, F, F, F, F, F, F, T, F, T, F, T, T, T},
            {F, F, T, F, F, F, F, F, F, F, T, F, T, T, F, F, F},
            {F, F, T, F, F, F, F, F, F, F, F, F, T, T, F, F, T},
            {F, F, F, F, F, T, F, F, F, F, T, F, T, T, F, T, F},
        };
        int[][] s7 = {
            {1, 2, 3, 4},
            {0, 5, 6, 11},
            {0, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15},
            {0, 2, 10, 13},
            {0, 2},
            {1, 2, 7, 8, 11, 12, 16},
            {1, 2, 9, 12},
            {2, 5},
            {2, 5},
            {2, 6, 10, 11, 12},
            {2, 3, 9, 13, 14, 16},
            {1, 2, 5, 9},
            {2, 5, 6, 9, 13, 14, 15, 16},
            {2, 3, 10, 12, 14, 15, 16},
            {2, 10, 12, 13},
            {2, 12, 13, 16},
            {5, 10, 12, 13, 15},
        };

        boolean[][] m8 = {
            {F, T, F, F, F, T, F, F, F, F, F, F, F, F, F, F, F},
            {T, F, T, T, T, F, T, F, T, F, F, F, F, F, F, F, F},
            {F, T, F, T, T, T, F, T, T, T, T, T, T, T, T, T, T},
            {F, T, T, F, F, F, F, F, F, F, F, T, T, T, F, F, T},
            {F, T, T, F, F, T, T, T, T, F, T, T, T, T, T, T, T},
            {T, F, T, F, T, F, F, T, F, F, F, F, F, F, F, F, F},
            {F, T, F, F, T, F, F, T, F, T, T, F, T, F, T, T, T},
            {F, F, T, F, T, T, T, F, F, T, F, F, T, F, F, F, F},
            {F, T, T, F, T, F, F, F, F, F, T, F, T, F, T, T, T},
            {F, F, T, F, F, F, T, T, F, F, T, F, F, F, F, F, F},
            {F, F, T, F, T, F, T, F, T, T, F, F, T, F, F, F, F},
            {F, F, T, T, T, F, F, F, F, F, F, F, F, F, T, F, F},
            {F, F, T, T, T, F, T, T, T, F, T, F, F, F, F, T, F},
            {F, F, T, T, T, F, F, F, F, F, F, F, F, F, T, T, T},
            {F, F, T, F, T, F, T, F, T, F, F, T, F, T, F, F, F},
            {F, F, T, F, T, F, T, F, T, F, F, F, T, T, F, F, F},
            {F, F, T, T, T, F, T, F, T, F, F, F, F, T, F, F, F},
        };
        int[][] s8 = {
            {1, 5},
            {0, 2, 3, 4, 6, 8},
            {1, 3, 4, 5, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16},
            {1, 2, 11, 12, 13, 16},
            {1, 2, 5, 6, 7, 8, 10, 11, 12, 13, 14, 15, 16},
            {0, 2, 4, 7},
            {1, 4, 7, 9, 10, 12, 14, 15, 16},
            {2, 4, 5, 6, 9, 12},
            {1, 2, 4, 10, 12, 14, 15, 16},
            {2, 6, 7, 10},
            {2, 4, 6, 8, 9, 12},
            {2, 3, 4, 14},
            {2, 3, 4, 6, 7, 8, 10, 15},
            {2, 3, 4, 14, 15, 16},
            {2, 4, 6, 8, 11, 13},
            {2, 4, 6, 8, 12, 13},
            {2, 3, 4, 6, 8, 13},
        };

        boolean[][] m9 = {
            {F, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T},
            {T, F, T, T, F, T, T, F, F, T, T, F, T, T, F, T, T},
            {T, T, F, T, F, F, T, F, F, F, F, F, F, F, F, F, F},
            {T, T, T, F, T, F, F, F, F, F, F, F, F, F, F, F, F},
            {T, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F, F},
            {T, T, F, F, F, F, F, T, T, F, T, T, T, T, T, T, T},
            {T, T, T, F, F, F, F, T, T, T, F, T, T, T, T, T, T},
            {T, F, F, F, F, T, T, F, F, F, T, T, T, T, T, F, T},
            {T, F, F, F, F, T, T, F, F, T, T, F, T, T, T, F, T},
            {T, T, F, F, F, F, T, F, T, F, F, F, F, T, F, T, F},
            {T, T, F, F, F, T, F, T, T, F, F, F, T, T, T, T, T},
            {T, F, F, F, F, T, T, T, F, F, F, F, F, F, F, F, F},
            {T, T, F, F, F, T, T, T, T, F, T, F, F, T, F, F, F},
            {T, T, F, F, F, T, T, T, T, T, T, F, T, F, T, F, F},
            {T, F, F, F, F, T, T, T, T, F, T, F, F, T, F, T, F},
            {T, T, F, F, F, T, T, F, F, T, T, F, F, F, T, F, T},
            {T, T, F, F, F, T, T, T, T, F, T, F, F, F, F, T, F},
        };
        int[][] s9 = {
            {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16},
            {0, 2, 3, 5, 6, 9, 10, 12, 13, 15, 16},
            {0, 1, 3, 6},
            {0, 1, 2, 4},
            {0, 3},
            {0, 1, 7, 8, 10, 11, 12, 13, 14, 15, 16},
            {0, 1, 2, 7, 8, 9, 11, 12, 13, 14, 15, 16},
            {0, 5, 6, 10, 11, 12, 13, 14, 16},
            {0, 5, 6, 9, 10, 12, 13, 14, 16},
            {0, 1, 6, 8, 13, 15},
            {0, 1, 5, 7, 8, 12, 13, 14, 15, 16},
            {0, 5, 6, 7},
            {0, 1, 5, 6, 7, 8, 10, 13},
            {0, 1, 5, 6, 7, 8, 9, 10, 12, 14},
            {0, 5, 6, 7, 8, 10, 13, 15},
            {0, 1, 5, 6, 9, 10, 14, 16},
            {0, 1, 5, 6, 7, 8, 10, 15},
        };

        boolean[][] m10 = {
            {F, T, T, F, F, F, F, F, F, F, F, F, T, F, T, F, F},
            {T, F, F, F, T, F, F, F, F, F, F, F, F, F, F, F, F},
            {T, F, F, T, F, F, T, F, F, T, T, F, F, F, F, F, F},
            {F, F, T, F, F, T, F, F, T, F, F, T, F, F, F, F, F},
            {F, T, F, F, F, F, T, F, F, F, F, F, F, F, F, F, F},
            {F, F, F, T, F, F, F, T, F, F, F, F, F, F, F, F, F},
            {F, F, T, F, T, F, F, T, F, T, T, F, T, T, F, F, F},
            {F, F, F, F, F, T, T, F, F, F, F, F, F, F, F, F, F},
            {F, F, F, T, F, F, F, F, F, F, T, F, F, F, F, F, F},
            {F, F, T, F, F, F, T, F, F, F, F, F, F, T, T, T, F},
            {F, F, T, F, F, F, T, F, T, F, F, T, T, T, T, F, T},
            {F, F, F, T, F, F, F, F, F, F, T, F, F, F, T, F, T},
            {T, F, F, F, F, F, T, F, F, F, T, F, F, T, T, T, F},
            {F, F, F, F, F, F, T, F, F, T, T, F, T, F, F, F, F},
            {T, F, F, F, F, F, F, F, F, T, T, T, T, F, F, T, F},
            {F, F, F, F, F, F, F, F, F, T, F, F, T, F, T, F, T},
            {F, F, F, F, F, F, F, F, F, F, T, T, F, F, F, T, F},
        };
        int[][] s10 = {
            {1, 2, 12, 14},
            {0, 4},
            {0, 3, 6, 9, 10},
            {2, 5, 8, 11},
            {1, 6},
            {3, 7},
            {2, 4, 7, 9, 10, 12, 13},
            {5, 6},
            {3, 10},
            {2, 6, 13, 14, 15},
            {2, 6, 8, 11, 12, 13, 14, 16},
            {3, 10, 14, 16},
            {0, 6, 10, 13, 14, 15},
            {6, 9, 10, 12},
            {0, 9, 10, 11, 12, 15},
            {9, 12, 14, 16},
            {10, 11, 15},
        };

        System.out.println(Graf.istiGraf(m1, s10));
        System.out.println(Graf.istiGraf(m2, s2));
        System.out.println(Graf.istiGraf(m3, s3));
        System.out.println(Graf.istiGraf(m4, s1));
        System.out.println(Graf.istiGraf(m5, s5));
        System.out.println(Graf.istiGraf(m6, s8));
        System.out.println(Graf.istiGraf(m7, s6));
        System.out.println(Graf.istiGraf(m8, s7));
        System.out.println(Graf.istiGraf(m9, s9));
        System.out.println(Graf.istiGraf(m10, s4));
    }
}
