
public class Test48 {

    private static final boolean T = true;
    private static final boolean F = false;

    public static void main(String[] args) {

        boolean[][] m1 = {
            {F, T, T, F, F, T, F, T, F, F, F, F, F, F, F},
            {T, F, F, F, F, F, F, F, F, T, F, F, F, F, F},
            {T, F, F, T, F, F, F, F, T, F, T, F, F, F, F},
            {F, F, T, F, T, T, T, F, F, F, F, T, F, F, T},
            {F, F, F, T, F, F, F, F, F, F, F, F, F, F, T},
            {T, F, F, T, F, F, F, F, F, F, F, F, F, F, F},
            {F, F, F, T, F, F, F, F, F, T, F, F, T, T, F},
            {T, F, F, F, F, F, F, F, F, T, F, F, T, T, F},
            {F, F, T, F, F, F, F, F, F, F, F, T, F, F, F},
            {F, T, F, F, F, F, T, T, F, F, T, T, T, T, T},
            {F, F, T, F, F, F, F, F, F, T, F, T, T, F, F},
            {F, F, F, T, F, F, F, F, T, T, T, F, F, F, F},
            {F, F, F, F, F, F, T, T, F, T, T, F, F, F, F},
            {F, F, F, F, F, F, T, T, F, T, F, F, F, F, T},
            {F, F, F, T, T, F, F, F, F, T, F, F, F, T, F},
        };
        int[][] s1 = {
            {1, 2, 5, 7},
            {0, 9},
            {0, 3, 8, 10},
            {2, 4, 5, 6, 11, 14},
            {3, 14},
            {0, 3},
            {3, 9, 12, 13},
            {0, 9, 12, 13},
            {2, 11},
            {1, 6, 7, 10, 11, 12, 13, 14},
            {2, 9, 11, 12},
            {3, 8, 9, 10},
            {6, 7, 9, 10},
            {6, 7, 9, 14},
            {3, 4, 9, 13},
        };

        boolean[][] m2 = {
            {F, T, T, F, T, F, F, T, F, F, F, F, F, F, F},
            {T, F, F, T, F, T, T, F, F, F, T, F, F, T, F},
            {T, F, F, F, F, F, F, T, T, T, F, F, T, T, F},
            {F, T, F, F, F, F, F, F, F, F, F, F, T, F, F},
            {T, F, F, F, F, F, F, F, F, T, F, F, F, F, F},
            {F, T, F, F, F, F, T, T, T, T, T, T, T, T, T},
            {F, T, F, F, F, T, F, F, F, F, F, F, F, F, F},
            {T, F, T, F, F, T, F, F, T, F, F, F, F, F, F},
            {F, F, T, F, F, T, F, T, F, F, F, F, F, F, T},
            {F, F, T, F, T, T, F, F, F, F, F, T, F, F, F},
            {F, T, F, F, F, T, F, F, F, F, F, F, F, F, F},
            {F, F, F, F, F, T, F, F, F, T, F, F, F, F, F},
            {F, F, T, T, F, T, F, F, F, F, F, F, F, F, T},
            {F, T, T, F, F, T, F, F, F, F, F, F, F, F, T},
            {F, F, F, F, F, T, F, F, T, F, F, F, T, T, F},
        };
        int[][] s2 = {
            {1, 2, 4, 7},
            {0, 3, 5, 6, 10, 13},
            {0, 7, 8, 9, 12, 13},
            {1, 12},
            {0, 9},
            {1, 6, 7, 8, 9, 10, 11, 12, 13, 14},
            {1, 5},
            {0, 2, 5, 8},
            {2, 5, 7, 14},
            {2, 4, 5, 11},
            {1, 5},
            {5, 9},
            {2, 3, 5, 14},
            {1, 2, 5, 14},
            {5, 8, 12, 13},
        };

        boolean[][] m3 = {
            {F, T, T, T, T, T, F, F, F, F, F, F, F, T, T},
            {T, F, T, T, T, T, T, T, T, T, T, T, T, T, T},
            {T, T, F, T, T, F, T, F, T, F, F, T, T, F, T},
            {T, T, T, F, F, F, F, F, F, F, F, F, T, F, F},
            {T, T, T, F, F, F, F, T, F, F, F, F, F, F, F},
            {T, T, F, F, F, F, T, F, F, T, T, F, T, T, F},
            {F, T, T, F, F, T, F, F, T, T, T, T, T, T, T},
            {F, T, F, F, T, F, F, F, F, F, F, F, F, F, F},
            {F, T, T, F, F, F, T, F, F, F, F, F, F, T, F},
            {F, T, F, F, F, T, T, F, F, F, F, F, F, F, T},
            {F, T, F, F, F, T, T, F, F, F, F, T, T, F, T},
            {F, T, T, F, F, F, T, F, F, F, T, F, F, F, F},
            {F, T, T, T, F, T, T, F, F, F, T, F, F, F, F},
            {T, T, F, F, F, T, T, F, T, F, F, F, F, F, T},
            {T, T, T, F, F, F, T, F, F, T, T, F, F, T, F},
        };
        int[][] s3 = {
            {1, 2, 3, 4, 5, 13, 14},
            {0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14},
            {0, 1, 3, 4, 6, 8, 11, 12, 14},
            {0, 1, 2, 12},
            {0, 1, 2, 7},
            {0, 1, 6, 9, 10, 12, 13},
            {1, 2, 5, 8, 9, 10, 11, 12, 13, 14},
            {1, 4},
            {1, 2, 6, 13},
            {1, 5, 6, 14},
            {1, 5, 6, 11, 12, 14},
            {1, 2, 6, 10},
            {1, 2, 3, 5, 6, 10},
            {0, 1, 5, 6, 8, 14},
            {0, 1, 2, 6, 9, 10, 13},
        };

        boolean[][] m4 = {
            {F, T, T, F, T, T, F, F, T, T, F, T, T, F, F},
            {T, F, T, T, F, F, F, F, F, T, F, F, F, F, F},
            {T, T, F, F, F, T, F, T, T, F, F, F, F, T, F},
            {F, T, F, F, T, T, T, T, T, T, T, T, T, T, T},
            {T, F, F, T, F, F, F, F, F, F, F, F, F, F, F},
            {T, F, T, T, F, F, T, F, F, F, F, F, F, F, F},
            {F, F, F, T, F, T, F, F, F, F, F, F, F, F, F},
            {F, F, T, T, F, F, F, F, F, F, F, F, F, F, F},
            {T, F, T, T, F, F, F, F, F, F, T, F, F, F, F},
            {T, T, F, T, F, F, F, F, F, F, F, T, F, F, F},
            {F, F, F, T, F, F, F, F, T, F, F, F, F, F, F},
            {T, F, F, T, F, F, F, F, F, T, F, F, F, F, T},
            {T, F, F, T, F, F, F, F, F, F, F, F, F, F, F},
            {F, F, T, T, F, F, F, F, F, F, F, F, F, F, F},
            {F, F, F, T, F, F, F, F, F, F, F, T, F, F, F},
        };
        int[][] s4 = {
            {1, 2, 4, 5, 8, 9, 11, 12},
            {0, 2, 3, 9},
            {0, 1, 5, 7, 8, 13},
            {1, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14},
            {0, 3},
            {0, 2, 3, 6},
            {3, 5},
            {2, 3},
            {0, 2, 3, 10},
            {0, 1, 3, 11},
            {3, 8},
            {0, 3, 9, 14},
            {0, 3},
            {2, 3},
            {3, 11},
        };

        boolean[][] m5 = {
            {F, T, T, T, T, T, T, T, T, T, T, T, T, T, T},
            {T, F, F, F, F, F, F, F, F, F, F, F, F, T, F},
            {T, F, F, T, F, T, F, F, F, T, F, F, F, F, F},
            {T, F, T, F, F, F, T, F, F, F, F, T, F, F, F},
            {T, F, F, F, F, F, F, T, F, F, F, F, F, F, F},
            {T, F, T, F, F, F, F, F, F, F, F, F, F, F, F},
            {T, F, F, T, F, F, F, F, F, F, F, F, F, F, F},
            {T, F, F, F, T, F, F, F, T, T, T, T, F, T, F},
            {T, F, F, F, F, F, F, T, F, T, T, F, T, T, T},
            {T, F, T, F, F, F, F, T, T, F, F, F, F, F, F},
            {T, F, F, F, F, F, F, T, T, F, F, T, T, F, T},
            {T, F, F, T, F, F, F, T, F, F, T, F, F, F, F},
            {T, F, F, F, F, F, F, F, T, F, T, F, F, T, F},
            {T, T, F, F, F, F, F, T, T, F, F, F, T, F, T},
            {T, F, F, F, F, F, F, F, T, F, T, F, F, T, F},
        };
        int[][] s5 = {
            {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14},
            {0, 13},
            {0, 3, 5, 9},
            {0, 2, 6, 11},
            {0, 7},
            {0, 2},
            {0, 3},
            {0, 4, 8, 9, 10, 11, 13},
            {0, 7, 9, 10, 12, 13, 14},
            {0, 2, 7, 8},
            {0, 7, 8, 11, 12, 14},
            {0, 3, 7, 10},
            {0, 8, 10, 13},
            {0, 1, 7, 8, 12, 14},
            {0, 8, 10, 13},
        };

        boolean[][] m6 = {
            {F, T, T, F, T, F, T, T, F, F, F, F, T, F, F},
            {T, F, F, T, F, F, F, F, F, F, F, F, F, F, F},
            {T, F, F, F, F, F, F, F, T, F, F, F, F, F, F},
            {F, T, F, F, F, F, F, F, F, T, F, T, F, F, T},
            {T, F, F, F, F, T, F, F, F, F, F, F, F, F, F},
            {F, F, F, F, T, F, F, F, F, F, F, F, F, T, F},
            {T, F, F, F, F, F, F, F, F, F, T, F, F, F, F},
            {T, F, F, F, F, F, F, F, F, F, F, T, T, T, F},
            {F, F, T, F, F, F, F, F, F, T, F, F, T, T, F},
            {F, F, F, T, F, F, F, F, T, F, F, F, F, F, F},
            {F, F, F, F, F, F, T, F, F, F, F, F, F, F, T},
            {F, F, F, T, F, F, F, T, F, F, F, F, F, F, F},
            {T, F, F, F, F, F, F, T, T, F, F, F, F, T, F},
            {F, F, F, F, F, T, F, T, T, F, F, F, T, F, F},
            {F, F, F, T, F, F, F, F, F, F, T, F, F, F, F},
        };
        int[][] s6 = {
            {1, 2, 4, 6, 7, 12},
            {0, 3},
            {0, 8},
            {1, 9, 11, 14},
            {0, 5},
            {4, 13},
            {0, 10},
            {0, 11, 12, 13},
            {2, 9, 12, 13},
            {3, 8},
            {6, 14},
            {3, 7},
            {0, 7, 8, 13},
            {5, 7, 8, 12},
            {3, 10},
        };

        boolean[][] m7 = {
            {F, T, T, F, F, F, F, F, F, F, T, F, F, T, F},
            {T, F, T, T, T, T, T, F, F, F, F, F, T, F, F},
            {T, T, F, F, F, F, F, F, F, F, F, F, F, F, F},
            {F, T, F, F, T, F, F, F, F, F, F, F, F, F, F},
            {F, T, F, T, F, F, T, F, F, F, F, F, F, F, T},
            {F, T, F, F, F, F, T, T, T, T, T, T, T, T, F},
            {F, T, F, F, T, T, F, T, F, T, F, F, T, F, F},
            {F, F, F, F, F, T, T, F, F, F, F, F, F, F, F},
            {F, F, F, F, F, T, F, F, F, F, F, F, F, T, F},
            {F, F, F, F, F, T, T, F, F, F, T, T, T, T, T},
            {T, F, F, F, F, T, F, F, F, T, F, T, F, F, F},
            {F, F, F, F, F, T, F, F, F, T, T, F, T, T, T},
            {F, T, F, F, F, T, T, F, F, T, F, T, F, T, F},
            {T, F, F, F, F, T, F, F, T, T, F, T, T, F, F},
            {F, F, F, F, T, F, F, F, F, T, F, T, F, F, F},
        };
        int[][] s7 = {
            {1, 2, 10, 13},
            {0, 2, 3, 4, 5, 6, 12},
            {0, 1},
            {1, 4},
            {1, 3, 6, 14},
            {1, 6, 7, 8, 9, 10, 11, 12, 13},
            {1, 4, 5, 7, 9, 12},
            {5, 6},
            {5, 13},
            {5, 6, 10, 11, 12, 13, 14},
            {0, 5, 9, 11},
            {5, 9, 10, 12, 13, 14},
            {1, 5, 6, 9, 11, 13},
            {0, 5, 8, 9, 11, 12},
            {4, 9, 11},
        };

        boolean[][] m8 = {
            {F, T, T, T, T, T, T, T, T, T, T, T, T, T, T},
            {T, F, T, T, T, F, T, T, T, T, T, F, T, T, T},
            {T, T, F, T, F, T, F, T, T, F, T, T, T, F, T},
            {T, T, T, F, T, T, T, F, T, T, T, T, T, T, F},
            {T, T, F, T, F, T, T, F, T, F, F, T, T, F, F},
            {T, F, T, T, T, F, F, T, F, F, F, T, F, F, F},
            {T, T, F, T, T, F, F, F, F, T, T, F, F, F, F},
            {T, T, T, F, F, T, F, F, T, F, T, T, T, T, T},
            {T, T, T, T, T, F, F, T, F, T, T, T, T, T, T},
            {T, T, F, T, F, F, T, F, T, F, T, F, F, F, F},
            {T, T, T, T, F, F, T, T, T, T, F, F, F, F, F},
            {T, F, T, T, T, T, F, T, T, F, F, F, F, T, F},
            {T, T, T, T, T, F, F, T, T, F, F, F, F, F, T},
            {T, T, F, T, F, F, F, T, T, F, F, T, F, F, F},
            {T, T, T, F, F, F, F, T, T, F, F, F, T, F, F},
        };
        int[][] s8 = {
            {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14},
            {0, 2, 3, 4, 6, 7, 8, 9, 10, 12, 13, 14},
            {0, 1, 3, 5, 7, 8, 10, 11, 12, 14},
            {0, 1, 2, 4, 5, 6, 8, 9, 10, 11, 12, 13},
            {0, 1, 3, 5, 6, 8, 11, 12},
            {0, 2, 3, 4, 7, 11},
            {0, 1, 3, 4, 9, 10},
            {0, 1, 2, 5, 8, 10, 11, 12, 13, 14},
            {0, 1, 2, 3, 4, 7, 9, 10, 11, 12, 13, 14},
            {0, 1, 3, 6, 8, 10},
            {0, 1, 2, 3, 6, 7, 8, 9},
            {0, 2, 3, 4, 5, 7, 8, 13},
            {0, 1, 2, 3, 4, 7, 8, 14},
            {0, 1, 3, 7, 8, 11},
            {0, 1, 2, 7, 8, 12},
        };

        boolean[][] m9 = {
            {F, T, T, T, F, T, T, T, T, T, T, T, F, T, F},
            {T, F, T, F, F, T, F, F, F, F, F, F, F, F, T},
            {T, T, F, F, T, F, F, F, F, F, F, T, F, F, F},
            {T, F, F, F, F, F, F, F, F, F, F, F, F, T, F},
            {F, F, T, F, F, F, F, T, F, F, F, F, F, F, F},
            {T, T, F, F, F, F, T, T, F, F, F, T, F, F, T},
            {T, F, F, F, F, T, F, F, F, F, F, F, F, F, F},
            {T, F, F, F, T, T, F, F, T, T, T, T, T, T, T},
            {T, F, F, F, F, F, F, T, F, F, T, F, F, T, F},
            {T, F, F, F, F, F, F, T, F, F, F, F, F, F, F},
            {T, F, F, F, F, F, F, T, T, F, F, F, T, T, T},
            {T, F, T, F, F, T, F, T, F, F, F, F, T, F, T},
            {F, F, F, F, F, F, F, T, F, F, T, T, F, T, F},
            {T, F, F, T, F, F, F, T, T, F, T, F, T, F, F},
            {F, T, F, F, F, T, F, T, F, F, T, T, F, F, F},
        };
        int[][] s9 = {
            {1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 13},
            {0, 2, 5, 14},
            {0, 1, 4, 11},
            {0, 13},
            {2, 7},
            {0, 1, 6, 7, 11, 14},
            {0, 5},
            {0, 4, 5, 8, 9, 10, 11, 12, 13, 14},
            {0, 7, 10, 13},
            {0, 7},
            {0, 7, 8, 12, 13, 14},
            {0, 2, 5, 7, 12, 14},
            {7, 10, 11, 13},
            {0, 3, 7, 8, 10, 12},
            {1, 5, 7, 10, 11},
        };

        boolean[][] m10 = {
            {F, T, T, T, F, F, F, F, F, F, F, F, F, T, F},
            {T, F, T, T, T, F, T, F, F, F, F, F, F, T, F},
            {T, T, F, T, T, T, F, F, T, T, T, T, F, F, F},
            {T, T, T, F, F, T, F, F, F, F, T, F, T, F, F},
            {F, T, T, F, F, F, T, F, T, F, F, F, F, F, F},
            {F, F, T, T, F, F, F, T, T, T, F, F, F, F, F},
            {F, T, F, F, T, F, F, F, T, T, F, F, F, F, F},
            {F, F, F, F, F, T, F, F, T, F, T, T, F, F, T},
            {F, F, T, F, T, T, T, T, F, F, F, F, F, T, F},
            {F, F, T, F, F, T, T, F, F, F, T, T, T, T, T},
            {F, F, T, T, F, F, F, T, F, T, F, F, F, F, F},
            {F, F, T, F, F, F, F, T, F, T, F, F, F, F, T},
            {F, F, F, T, F, F, F, F, F, T, F, F, F, F, F},
            {T, T, F, F, F, F, F, F, T, T, F, F, F, F, F},
            {F, F, F, F, F, F, F, T, F, T, F, T, F, F, F},
        };
        int[][] s10 = {
            {1, 2, 3, 13},
            {0, 2, 3, 4, 6, 13},
            {0, 1, 3, 4, 5, 8, 9, 10, 11},
            {0, 1, 2, 5, 10, 12},
            {1, 2, 6, 8},
            {2, 3, 7, 8, 9},
            {1, 4, 8, 9},
            {5, 8, 10, 11, 14},
            {2, 4, 5, 6, 7, 13},
            {2, 5, 6, 10, 11, 12, 13, 14},
            {2, 3, 7, 9},
            {2, 7, 9, 14},
            {3, 9},
            {0, 1, 8, 9},
            {7, 9, 11},
        };

        System.out.println(Graf.istiGraf(m1, s1));
        System.out.println(Graf.istiGraf(m2, s2));
        System.out.println(Graf.istiGraf(m3, s4));
        System.out.println(Graf.istiGraf(m4, s3));
        System.out.println(Graf.istiGraf(m5, s5));
        System.out.println(Graf.istiGraf(m6, s6));
        System.out.println(Graf.istiGraf(m7, s10));
        System.out.println(Graf.istiGraf(m8, s8));
        System.out.println(Graf.istiGraf(m9, s9));
        System.out.println(Graf.istiGraf(m10, s7));
    }
}
